begin;

create table if not exists public.booking_messages (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  sender_user_id uuid references auth.users(id) on delete set null,
  sender_role text not null check (sender_role in ('customer', 'rider')),
  message text not null check (
    char_length(btrim(message)) between 1 and 1000
  ),
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists booking_messages_order_created_idx
  on public.booking_messages (order_id, created_at asc, id asc);

create index if not exists booking_messages_unread_idx
  on public.booking_messages (order_id, sender_role, read_at)
  where read_at is null;

alter table public.booking_messages enable row level security;

-- Messages are accessed only through server-side API routes after checking
-- that the signed-in user owns the booking or is its assigned rider.
revoke all on public.booking_messages from anon, authenticated;
grant all on public.booking_messages to service_role;

-- Identity sequence permission is included explicitly for service-role inserts.
do $$
declare
  sequence_name text;
begin
  sequence_name := pg_get_serial_sequence(
    'public.booking_messages',
    'id'
  );

  if sequence_name is not null then
    execute format(
      'grant usage, select on sequence %s to service_role',
      sequence_name
    );
  end if;
end
$$;

commit;
