begin;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  order_id bigint references public.orders(id) on delete cascade,
  booking_no text,
  recipient_type text not null check (recipient_type in ('customer', 'rider', 'admin')),
  recipient_user_id uuid references auth.users(id) on delete cascade,
  notification_type text not null,
  title text not null,
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_recipient_created_idx
  on public.notifications (recipient_type, recipient_user_id, created_at desc);
create index if not exists notifications_order_idx
  on public.notifications (order_id);

alter table public.notifications enable row level security;
revoke all on public.notifications from anon, authenticated;
grant all on public.notifications to service_role;

commit;
